# -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

# def options(opt):
#     pass

# def configure(conf):
#     conf.check_nonfatal(header_name='stdint.h', define_name='HAVE_STDINT_H')

def build(bld):
    module = bld.create_ns3_module('sdn', ['network','internet'])
    module.source = [
        'model/sdn.cc',
        'helper/sdn-helper.cc',
        'model/sdn-flowtable.cc',
        'model/sdn-id-lookup-table.cc',
        'model/sdn-netview.cc',
        'model/sdn-packet.cc',
        'model/sdn-rqueue.cc',
        ]

    module_test = bld.create_ns3_module_test_library('sdn')
    module_test.source = [
        'test/sdn-test-suite.cc',
        ]
    # Tests encapsulating example programs should be listed here
    if (bld.env['ENABLE_EXAMPLES']):
        module_test.source.extend([
        #    'test/sdn-examples-test-suite.cc',
             ])

    headers = bld(features='ns3header')
    headers.module = 'sdn'
    headers.source = [
        'model/sdn.h',
        'helper/sdn-helper.h',
        'model/sdn-flowtable.h',
        'model/sdn-id-lookup-table.h',
        'model/sdn-netview.h',
        'model/sdn-packet.h',
        'model/sdn-rqueue.h',
        ]

    if bld.env.ENABLE_EXAMPLES:
        bld.recurse('examples')

    # bld.ns3_python_bindings()

